[providers]
node = "18"

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build completed'"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"